### ISSUE TITLE
Minimal list of operational transformations of graph structures (cards env)

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/cards#5]
if we end up building an OT for graphs/patchers, then we want a minimal list of atomic edits in a patching environment. we can edit this here:

# Minimal Operational Transformations:

### movement-based
- dragging object: start-point, end-point

### unsorted/unnamed
- new card
- update card text
- update card attribute
- connect output of card _a__ to input of card _b__
- move connection to a different input or output
- disable connection
- duplicate, cut, paste (& copy?)
- resize card
- selection
- comment out some code
- add/remove comment
- save, save as...
- create link between a card and other content (voice memo, article, paper annotation, other project, etc)

### 'ephemeral' transformations
- user(s) positional data
- orientation/position/scale/etc of whole card graph in vr space
- library interaction (search history)

**Comment by michaelpalumbo** [comment]
is 'undo' a transformation itself?

**Comment by grrrwaaa** [comment]
Moved to wiki: https://github.com/worldmaking/cards/wiki/List-of-Operational-Transforms
